export const MOCK_GUEST_BOOKS = [
  {
    id: 1,
    content: '모모야 결혼 너무 축하해! 두 사람의 앞날에 언제나 행복만 가득하길!',
    from: '이뫄뫄',
    miniMeId: 3,
  },
  {
    id: 2,
    content: '신혼여행도 조심히 잘 다녀오고 사진 많이 공유해줘!',
    from: '김모모',
    miniMeId: 15,
  },
  {
    id: 3,
    content: '늘 서로를 존중하며 사랑하는 부부가 되길 응원할게 :)',
    from: '동기 일동',
    miniMeId: 22,
  },
  {
    id: 4,
    content: '언제나 지금처럼만 웃는 날들만 이어져라!',
    from: '친구들',
    miniMeId: 9,
  },
  {
    id: 5,
    content: '결혼 진심으로 축하해! 평생 행복하게 살아!',
    from: '박짱구',
    miniMeId: 7,
  },
  {
    id: 6,
    content: '두 분의 사랑이 영원하길 바랍니다 💕',
    from: '최유리',
    miniMeId: 12,
  },
  {
    id: 7,
    content: '오래오래 행복하게~!',
    from: '송하나',
    miniMeId: 1,
  },
  {
    id: 8,
    content: '축하해! 신혼생활 화이팅!',
    from: '정민수',
    miniMeId: 18,
  },
  {
    id: 9,
    content: '결혼 축하드려요! 항상 웃음이 넘치는 가정 이루시길!',
    from: '이서연',
    miniMeId: 25,
  },
  {
    id: 10,
    content: '평생 서로 아끼며 사세요!',
    from: '강태양',
    miniMeId: 4,
  },
  {
    id: 11,
    content: '두 분 정말 잘 어울려요! 축하합니다!',
    from: '윤별',
    miniMeId: 31,
  },
  {
    id: 12,
    content: '결혼 축하해요~ 행복한 가정 꾸리세요!',
    from: '조은비',
    miniMeId: 14,
  },
  {
    id: 13,
    content: '백년해로 하세요!',
    from: '한지민',
    miniMeId: 20,
  },
  {
    id: 14,
    content: '너무 축하해! 신혼여행 재밌게 다녀와!',
    from: '배수지',
    miniMeId: 6,
  },
  {
    id: 15,
    content: '행복한 결혼생활 되길 바랄게!',
    from: '오준혁',
    miniMeId: 29,
  },
  {
    id: 16,
    content: '평생 지금처럼 사랑하며 사세요!',
    from: '임하늘',
    miniMeId: 11,
  },
  {
    id: 17,
    content: '결혼 진심 축하해! 오래오래 행복해!',
    from: '서민재',
    miniMeId: 8,
  },
  {
    id: 18,
    content: '두 분의 앞날에 축복이 가득하길!',
    from: '김소라',
    miniMeId: 27,
  },
  {
    id: 19,
    content: '항상 건강하고 행복하세요!',
    from: '이준호',
    miniMeId: 2,
  },
  {
    id: 20,
    content: '결혼 축하드립니다! 평생 행복하세요!',
    from: '박지은',
    miniMeId: 16,
  },
  {
    id: 21,
    content: '신랑신부 모두 축하해요!',
    from: '최다온',
    miniMeId: 23,
  },
  {
    id: 22,
    content: '평생 서로 사랑하며 행복하게!',
    from: '강예린',
    miniMeId: 5,
  },
  {
    id: 23,
    content: '결혼 정말 축하해! 행복만 하자!',
    from: '윤재현',
    miniMeId: 30,
  },
  {
    id: 24,
    content: '두 분 정말 잘 맞는 한 쌍!',
    from: '조아라',
    miniMeId: 13,
  },
  {
    id: 25,
    content: '평생 지금처럼 웃으며 사세요!',
    from: '한승우',
    miniMeId: 19,
  },
  {
    id: 26,
    content: '축하해요! 행복한 신혼생활 되세요!',
    from: '배시은',
    miniMeId: 10,
  },
  {
    id: 27,
    content: '결혼 축하드려요! 오래오래 행복하세요!',
    from: '오민지',
    miniMeId: 28,
  },
  {
    id: 28,
    content: '평생 행복하게 살아요!',
    from: '임태민',
    miniMeId: 17,
  },
  {
    id: 29,
    content: '축하합니다! 항상 웃음 가득한 가정 이루시길!',
    from: '서유나',
    miniMeId: 24,
  },
  {
    id: 30,
    content: '결혼 축하해! 평생 사랑해!',
    from: '김하늘',
    miniMeId: 32,
  },
];
